### ISSUE TITLE
Wolfram Alpha and the FAQ sheet

### ISSUE THREAD

**Issue by freeradical777** [danfiscus/Algernon#1]
Dan, you should put in the faq section, where you say there aren't many programs that show the steps, that we will also not charge you money for a "pro" account.

**Comment by freeradical777** [comment]
nevermind I forgot it was a wiki

**Comment by ChristopherKing42** [comment]
It was closed by bfe8da1

**Comment by ChristopherKing42** [comment]
We could have a donation button though:
https://www.paypal.com/us/cgi-bin/?cmd=_donate-intro-outside
