### ISSUE TITLE
I can't use Glade...

### ISSUE THREAD

**Issue by danfiscus** [danfiscus/Algernon#2]
I have no idea why. I've tried all kinds of stuff, and I just can't make it work. I really want to see what we have to far, but I don't know how. Any suggestions?

**Comment by ChristopherKing42** [comment]
Wubi

**Comment by danfiscus** [comment]
@TheKing42 What? [Did you mean this?](http://en.wikipedia.org/wiki/Wow!_Wow!_Wubbzy!)

**Comment by ChristopherKing42** [comment]
That is wubbzy, not wubi.
https://wiki.ubuntu.com/WubiGuide

**Comment by freeradical777** [comment]
Why does he need a wubi install?

**Comment by danfiscus** [comment]
@TheKing42 lol ok. So basically install ubuntu?

**Comment by ChristopherKing42** [comment]
Glade doesn't work well with nonlinux apparently.

**Comment by danfiscus** [comment]
@TheKing42 Ok, I'll try installing Ubuntu using Parallels and see how that works.

**Comment by ChristopherKing42** [comment]
That works too (also, if regular ubuntu is hard on resources, use lubuntu.
It is just as good for our needs well being much smaller and lighter,
although have a more basic look.)

**Comment by danfiscus** [comment]
Well the download for ubuntu is a gigabyte. Also, wubi is only for windows, so i can't use it anyway. That would be a VM inside a VM. Too much inception for one day. Where is lububtu

**Comment by ChristopherKing42** [comment]
http://lubuntu.net/
I recommend the torrent option. It is much faster.

**Comment by danfiscus** [comment]
@TheKing42 Ok, thanks! You're pretty sure it will run Glade?

**Comment by ChristopherKing42** [comment]
Definitely
Or if you want the most newest bleeding edge version, use Arch (you
don't want the most newest bleeding edge version by the way.)

**Comment by freeradical777** [comment]
It should. Chris has a lubuntu machine

**Comment by danfiscus** [comment]
Haha, ok thanks for reminding me what I want, Chris! ;)
It's always good to have someone remind you of your opinions. Lol

**Comment by ChristopherKing42** [comment]
I bet that glade would look cool on ubuntu studio.
