### ISSUE TITLE
Glade file is broken?

### ISSUE THREAD

**Issue by danfiscus** [danfiscus/Algernon#4]
I was up for another round of frustration, so I spent a few hours working with glade this weekend. No matter what I try, I can not for the life of me get anything to work. I finally got glade to open, and it seems functional, but when I tried to open the file on this repository, it was blank. I give up. Would wxwidgets work for our needs or would we need something else? We should abandon glade before it's too late, I don't want to be the leader of a project I can't even open... lol

**Comment by danfiscus** [comment]
I'm not trying to be bossy here btw, it's just not feasible at this point to keep using glade. Trust me i've tried everything.

**Comment by freeradical777** [comment]
Well we have 2 options then. Option 1 is we switch to another gui builder or build the gui ourselves using GTK libraries. Option 2 is dan finds another job but we keep glade. I think we should hold a vote, so cast in the google hangout we have open or comment below. This way it's 100% fair.

**Comment by freeradical777** [comment]
Oh, and I vote option 1 by the way. More practice, higher quality.

**Comment by ChristopherKing42** [comment]
It appears I have used an older version of glade. I vote we just rebuild
the gui with the newest version of glade.

**Comment by freeradical777** [comment]
Ohh, it could just be compatibility issue. Try to rebuild and have dan try it.

**Comment by ChristopherKing42** [comment]
I tried the updated glade as well, and it didn't work.

**Comment by ChristopherKing42** [comment]
Wait dan, what version were you using. I am using Glade 3.16.1
