### ISSUE TITLE
Where are we?

### ISSUE THREAD

**Issue by danfiscus** [danfiscus/Algernon#5]
I'd love to see this project get going again!

**Comment by freeradical777** [comment]
I would too!

How far are you in c++ class?I believe we as a group are only as far as you and chris are. I am farther ahead of you guys in c++ knowledge, but i don't want to rush so far ahead you guys have no chance to participate. 

The next step should be building a simple arithmetic parser (which i started on). It's challenging but not too hard if you have knowledge of data structures.
